#pragma once

#ifndef CONFIG_GOLIOTH_COAP_HOST_URI
#define CONFIG_GOLIOTH_COAP_HOST_URI "coaps://coap.golioth.io"
// #define CONFIG_GOLIOTH_COAP_HOST_URI "coaps://192.168.86.240"
#endif

#ifndef CONFIG_GOLIOTH_COAP_RESPONSE_TIMEOUT_S
#define CONFIG_GOLIOTH_COAP_RESPONSE_TIMEOUT_S 10
#endif

#ifndef CONFIG_GOLIOTH_COAP_REQUEST_QUEUE_TIMEOUT_MS
#define CONFIG_GOLIOTH_COAP_REQUEST_QUEUE_TIMEOUT_MS 1000
#endif

#ifndef CONFIG_GOLIOTH_COAP_REQUEST_QUEUE_MAX_ITEMS
#define CONFIG_GOLIOTH_COAP_REQUEST_QUEUE_MAX_ITEMS 10
#endif

#ifndef CONFIG_GOLIOTH_COAP_TASK_PRIORITY
#define CONFIG_GOLIOTH_COAP_TASK_PRIORITY 5
#endif

#ifndef CONFIG_GOLIOTH_COAP_TASK_STACK_SIZE_BYTES
#define CONFIG_GOLIOTH_COAP_TASK_STACK_SIZE_BYTES 6144
#endif

#ifndef CONFIG_GOLIOTH_COAP_KEEPALIVE_INTERVAL_S
#define CONFIG_GOLIOTH_COAP_KEEPALIVE_INTERVAL_S 9
#endif

#ifndef CONFIG_GOLIOTH_MAX_NUM_OBSERVATIONS
#define CONFIG_GOLIOTH_MAX_NUM_OBSERVATIONS 8
#endif

#ifndef CONFIG_GOLIOTH_OTA_MAX_PACKAGE_NAME_LEN
#define CONFIG_GOLIOTH_OTA_MAX_PACKAGE_NAME_LEN 64
#endif

#ifndef CONFIG_GOLIOTH_OTA_MAX_VERSION_LEN
#define CONFIG_GOLIOTH_OTA_MAX_VERSION_LEN 64
#endif

#ifndef CONFIG_GOLIOTH_OTA_MAX_NUM_COMPONENTS
#define CONFIG_GOLIOTH_OTA_MAX_NUM_COMPONENTS 4
#endif

#ifndef CONFIG_GOLIOTH_COAP_MAX_PATH_LEN
#define CONFIG_GOLIOTH_COAP_MAX_PATH_LEN 39
#endif

#ifndef CONFIG_GOLIOTH_RPC_ENABLE
#define CONFIG_GOLIOTH_RPC_ENABLE 1
#endif

#ifndef CONFIG_GOLIOTH_SETTINGS_ENABLE
#define CONFIG_GOLIOTH_SETTINGS_ENABLE 1
#endif

#ifndef CONFIG_GOLIOTH_RPC_MAX_NUM_METHODS
#define CONFIG_GOLIOTH_RPC_MAX_NUM_METHODS 8
#endif

#ifndef CONFIG_GOLIOTH_ALLOCATION_TRACKING
#define CONFIG_GOLIOTH_ALLOCATION_TRACKING 0
#endif
