manifest:
  self:
    path: modules/lib/golioth-firmware-sdk
    import:
      file: west-zephyr.yml
      name-allowlist:
        - cmsis
        - hal_espressif
        - hal_nordic
        - hal_nxp
        - hal_stm32
        - littlefs
        - mbedtls
        - mcuboot
        - net-tools
        - picolibc
        - segger
        - zcbor
        - zephyr
