manifest:
  self:
    path: modules/lib/golioth-firmware-sdk
    import:
      file: west-ncs.yml
      name-allowlist:
        - cmsis_6
        - hal_nordic
        - littlefs
        - mbedtls
        - mcuboot
        - net-tools
        - nrf
        - nrfxlib
        - oberon-psa-crypto
        - openthread
        - segger
        - trusted-firmware-m
        - zcbor
        - zephyr
