/*
 * Copyright (c) 2024 Golioth, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#define CONFIG_GOLIOTH_AUTO_LOG_TO_CLOUD 1
#define CONFIG_GOLIOTH_COAP_REQUEST_QUEUE_MAX_ITEMS 20
#define CONFIG_GOLIOTH_DEBUG_LOG
#define CONFIG_GOLIOTH_FW_UPDATE
#define CONFIG_GOLIOTH_LIGHTDB_STATE
#define CONFIG_GOLIOTH_RPC
#define CONFIG_GOLIOTH_SETTINGS
#define CONFIG_GOLIOTH_STREAM
