name: Mask secrets in files

description: |
  Crawl the current tree, finding any GitHub secret and replacing it with
  ***NAME_OF_SECRET***

inputs:
  secrets-json:
    description: 'Secrets context to be masked, in JSON format'
    required: true

runs:
  using: composite
  steps:
    - name: Find and mask
      shell: bash
      env:
        SECRETS_CONTEXT: '${{ inputs.secrets-json }}'
      run: |
        if ! command -v jq; then
          apt update && apt install -y jq
        fi

        for key in $(jq -r "keys[]" <<< "$SECRETS_CONTEXT");
        do
          secret_val=$(jq -r ".$key" <<< "$SECRETS_CONTEXT")

          if [[ ! $secret_val =~ "\n" ]]; then
            # This approach to escaping the regex found: https://stackoverflow.com/a/29613573/922013
            ESCAPED_SECRET=$(sed 's/[^^]/[&]/g; s/\^/\\^/g' <<< "$secret_val")

            # Always return true, otherwise a grep that doesn't find files will cause step to fail
            [ $(grep -Rl $ESCAPED_SECRET | xargs -I{} sed -i "s/$ESCAPED_SECRET/***$key***/g" {}) >= 0 ]
          fi
        done
