name: "CI: Coverity"

on:
  workflow_dispatch:
  push:
    branches:
      - coverity_ci

jobs:
  coverity:
    runs-on: ubuntu-24.04
    container: golioth/golioth-zephyr-base:0.17.0-SDK-v0

    steps:
      - uses: actions/checkout@v4
        with:
          path: modules/lib/golioth-firmware-sdk
          submodules: recursive
      - name: Init and update west
        run: |
          mkdir -p .west
          cat <<EOF > .west/config
          [manifest]
          path = modules/lib/golioth-firmware-sdk
          file = west-zephyr.yml
          EOF

          west update -o=--depth=1 -n

          pip3 install \
            -r zephyr/scripts/requirements-base.txt \
            -r zephyr/scripts/requirements-build-test.txt \
            -r zephyr/scripts/requirements-run-test.txt

          # Needed for TF-M
          pip3 install \
            cryptography==41.0.7 \
            pyasn1 \
            pyyaml \
            cbor>=1.0.0 \
            imgtool>=1.9.0 \
            jinja2 \
            click
      - run: |
          apt-get update
          apt-get install -y curl
          curl https://scan.coverity.com/download/cxx/linux64 -o coverity.tar.gz --data "token=t3GgbbHg2ZGYtCBJnTDDRw&project=golioth%2Fgolioth-firmware-sdk"
          tar -xvf coverity.tar.gz
          ./ccov-analysis-linux64-2024.6.1/bin/cov-configure --comptype gcc --compiler /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
          ./cov-analysis-linux64-2024.6.1/bin/cov-build --dir cov-int west build -p -b modules/lib/golioth-firmware-sdk/examples/hello
