name: "CI: Coverity"

on:
  schedule:
    # Run workflow every Sunday
    - cron: "00 0 * * 0"
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-24.04
    # yamllint disable-line rule:line-length
    container: golioth/golioth-coverity-base:ee62f47-sdk-0.17.4@sha256:a301b19ff552b8ec3db88a0bc452186bbee9d15ce6ef4d430530d6b52af9a11a

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: modules/lib/golioth-firmware-sdk
          submodules: recursive
      - name: Init and update west
        run: |
          mkdir -p .west
          cat <<EOF > .west/config
          [manifest]
          path = modules/lib/golioth-firmware-sdk
          file = west-zephyr.yml
          EOF

          west update -o=--depth=1 -n

          uv pip install \
            -r zephyr/scripts/requirements-base.txt \
            -r zephyr/scripts/requirements-build-test.txt \
            -r zephyr/scripts/requirements-run-test.txt

          # Needed for TF-M
          uv pip install \
            cryptography==41.0.7 \
            pyasn1 \
            pyyaml \
            cbor>=1.0.0 \
            imgtool>=1.9.0 \
            jinja2 \
            click
      - run: |
          /opt/toolchains/coverity/bin/cov-configure --comptype gcc \
            --compiler /opt/toolchains/zephyr-sdk-0.17.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
          /opt/toolchains/coverity/bin/cov-build --dir cov-int \
            west build -p -b nrf52840dk/nrf52840 \
            modules/lib/golioth-firmware-sdk/examples/zephyr/fw_update \
            -- -DCONFIG_NET_LOG=n -DCONFIG_LOG=n
          tar czvf golioth-firmware-sdk.tgz cov-int
          curl --form token=${{ secrets.COVERITY_TOKEN }} \
            --form email=sam@golioth.io \
            --form file=@golioth-firmware-sdk.tgz \
            --form version="0" \
            --form description="Description" \
            https://scan.coverity.com/builds?project=golioth%2Fgolioth-firmware-sdk
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverity_output
          path: golioth-firmware-sdk.tgz
