name: "CI: Clean Project"

on:
  schedule:
    # Run workflow at the start of every day (11 PM UTC)
    - cron: "0 23 * * *"

jobs:
  check_versions:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.11' # >=3.11 for datetime.fromisoformat()

      - name: Install Golioth Python Tools
        run: |
          pip install git+https://github.com/golioth/python-golioth-tools@v0.9.0

      - name: Remove old asset from Prod
        run: |
          python3 scripts/ci/clean_ci_project "${{ secrets.PROD_CI_PROJECT_API_KEY }}" \
                  --api-url "https://api.golioth.io"                                   \
                  --days-old 1

      - name: Remove old asset from Dev
        run: |
          python3 scripts/ci/clean_ci_project "${{ secrets.DEV_CI_PROJECT_API_KEY }}"  \
                  --api-url "https://api.golioth.dev"                                  \
                  --days-old 1
