name: "CI: pre-commit"

on:
  pull_request:

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04

    container:
      # yamllint disable-line rule:line-length
      image: kiwicom/pre-commit:3.6.0@sha256:381a3406aa9e6fedfc386ca0889dd5b8e9b915cbc5490a3ecec272ed7b8a67ed

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Run pre-commit
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          CODE=0 # run pre-commit
          for CID in $(git rev-list --reverse origin/$GITHUB_BASE_REF..); do
              git show $CID -s --format='    pre-commit %h ("%s")'
              git checkout -f -q $CID
              pre-commit run \
                --color always \
                --show-diff-on-failure \
                --from-ref $CID^ \
                --to-ref $CID \
                || CODE=$?
          done
          exit $CODE
