name: "CI: yamllint"

on:
  pull_request:

  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run yamllint
        run: |
          yamllint -f github .
