name: "CI: yamllint"

on:
  pull_request:

  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run yamllint
        run: |
          yamllint -f github .
