name: Deploy Doxygen to Firebase Hosting on PR
'on': pull_request_target
jobs:
  deploy_doxygen_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt install doxygen graphviz
      - name: Generate Doxygen
        run: |
          cd docs/doxygen
          doxygen
      - name: Deploy docs to dev
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLIOTH }}'
          projectId: golioth
          target: docs-dev
          entryPoint: docs
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
