name: Deploy Doxygen to Firebase Hosting on PR
on: pull_request
jobs:
  deploy_doxygen_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: |
          sudo apt install wget graphviz
          wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
          tar -xvf doxygen-1.10.0.linux.bin.tar.gz
          cd doxygen-1.10.0
          sudo make install
      - name: Generate Doxygen
        run: |
          cd docs/doxygen
          doxygen
      - name: Deploy docs to dev
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLIOTH }}'
          projectId: golioth
          target: docs-dev
          entryPoint: docs
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
