name: Deploy Doxygen to Firebase Hosting on Main
'on':
  push:
    branches:
      - main
jobs:
  deploy_doxygen_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: |
          sudo apt install wget graphviz
          wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
          tar -xvf doxygen-1.10.0.linux.bin.tar.gz
          cd doxygen-1.10.0
          sudo make install
      - name: Generate Doxygen
        run: |
          cd docs/doxygen
          doxygen
      - uses: FirebaseExtended/action-hosting-deploy@ac8041b3b04337509168113bf98b95879df22322
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLIOTH }}'
          channelId: live
          projectId: golioth
          target: docs-prod
          entryPoint: docs
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
